set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

" load pathogen
call pathogen#infect()

" base customization
set number
set ruler
syntax on

" Set encoding
set encoding=utf-8

" indent
set smartindent
set autoindent

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Show (partial) command in the status line
set showcmd

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Status bar
set laststatus=2

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Set font
if has("gui_running")
  if has("gui_win32")
    set guifont=consolas:h10:cANSI
    set guioptions-=T
    set guioptions-=m
  endif
endif

" Default color scheme
color desert
" quiet linenumber
hi LineNr guifg=#505050

" Directories for swp files
set backupdir=~/vimtmp/backup
set directory=~/vimtmp/backup

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" map Leader key to ,
let mapleader = ","

:command C let @/=""
